version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.4.3

jobs:
  test:
    docker:
      - image: cimg/node:20.4.0
    steps:
      - browser-tools/install-browser-tools:
          chrome-version: 114.0.5735.198
      - browser-tools/install-chromedriver
      - run:
          name: "Verify Chrome Install"
          command: |
            rm -f ~/project/LICENSE.chromedriver
            google-chrome --version
            chromedriver --version

workflows:
  version: 2
  build-and-test:
    jobs:
      - test
